x-base:
  &base
  env_file:
    - ./.env
  networks:
    - squidshop-network
  restart: always

services:
  postgres:
    <<: *base
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    container_name: squidshop-postgres
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  migrate:
    <<: *base
    image: migrate/migrate
    container_name: squidshop-migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "./migrations", "-database", "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/postgres?sslmode=disable", "up" ]
    restart: on-failure
    depends_on:
      - postgres

  redis:
    <<: *base
    image: redis:7.4-alpine
    container_name: squidshop-redis
    volumes:
      - /redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  backend:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: squidshop-backend
    depends_on:
      - migrate
      - redis

networks:
  squidshop-network:
    name: squidshop-network
    driver: bridge

volumes:
  postgres-data:
  redis-data:
