basePath: /api/v1
host: api.squidshop.ir
info:
  contact:
    email: arshamdev2001@gmail.com
    name: Arsham Roshannejad
    url: arshamroshannejad.ir
  description: Api for managing product and everything related to E-commerce shop
  license:
    name: MIT
    url: https://www.mit.edu/~amini/LICENSE.md
  termsOfService: http://swagger.io/terms/
  title: squidshop-backend
  version: 0.1.0
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
